### ISSUE TITLE
Wrong version of mssqlodbc installed or docs are wrong

### ISSUE THREAD

**Issue by traviscook21** [Microsoft/homebrew-mssql-release#12]
When following the directions posted on this page:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#os-x-1011-el-capitan-macos-1012-sierra-and-macos-1013-high-sierra

I would expect mssqlodbc to be installed at version 17.

However, this repo clearly shows that the ODBC driver installed is version 13.1.  How do I install version 17 on Mac OSX using brew?

**Comment by David-Engel** [comment]
@traviscook21 We are still working through an issue on the new homebrew formulas. We will have it updated as soon as we can.

David

**Comment by awaistariq** [comment]
I have the same issue. 
![screen shot 2018-02-20 at 2 15 43 pm](https://user-images.githubusercontent.com/3714825/36421189-97decdf0-1648-11e8-9199-ff051212f817.png)

**Comment by awaistariq** [comment]
@traviscook21  did you find any solution?

**Comment by traviscook21** [comment]
My "solution" is to assume the driver installed for MacOS is at version 13.  Interestingly, I also found that when I installed the mssql driver using apt-get in Docker using a Debian image, it is now also installing version 13 (it was previously installing 17)

**Comment by David-Engel** [comment]
@awaistariq @traviscook21 
The ODBC driver team is still working on fixing the upgrade story when updating to v17 from v13. Until it is fixed, the 13.1 version is the latest available on Linux and Mac. There is a note posted on the installation page:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#microsoft-odbc-driver-17-for-sql-server

Please be patient. We will have v17 available as soon as possible.

Thanks,
David

**Comment by David-Engel** [comment]
The v17 driver package for mac has been posted and an updated brew formula is available for use.

David
