### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by David-Engel** [Microsoft/homebrew-mssql-release#13]
Filing from a comment here:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server

Swabips 5 hours ago
 I get this error when updating on OS X High Sierra:

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/microsoft/homebrew-msodbcsql/Formula/msodbcsql.rb:16:in `caveats'
Please report this to the microsoft/msodbcsql tap!

How do I fix this to update?

**Comment by v-sutso** [comment]
I update the formula msodbcsql17.rb and msodbcsql17@17.0.1.1.rb in the sqlbuilds folder to fix the warning issue.

**Comment by David-Engel** [comment]
This warning should no longer appear after the next time you run `brew update`.
