### ISSUE TITLE
sqlcmd does not accept queries from standard input

### ISSUE THREAD

**Issue by mkormendy** [Microsoft/homebrew-mssql-release#2]
Per the issue here: https://github.com/mtxr/SQLTools/issues/120 the sqlcmd command does not seem to accept queries from the stdin approach, by piping the query into the command or otherwise. 
The simple test that was performed was:

```
echo "select 1;" | sqlcmd -S "serverorIP,port" -U "username" -P "password" -d "database"
```

It returns:

```
Sqlcmd: Warning: The last operation was terminated because the user pressed CTRL+C.
```

I realize that this is the github repo for the homebrew installer for sqlcmd, however it appears that the maintainer of the sqlcmd CLI is the poster of this installer as well.

**Comment by meet-bhagdev** [comment]
@mkormendy thanks for reporting the issue! 
@abhisheksinha89 can you take a look?

**Comment by tkopets** [comment]
Please note that on Windows `sqcmd` works with stdin as expected, but on Mac it doesn't.
Most probably it doesn't work on Linux platforms as well (not tested).

**Comment by tkopets** [comment]
@meet-bhagdev 
@abhisheksinha89 
Do you have any updates on this issue?
Please let me know if you need more info or if I can help you in any other way?

**Comment by abhisheksinha89** [comment]
Yes we do not support reading from stdin for sqlcmd/bcp on *nix platforms for now. Currently fixing this is not in our near term roadmap, however please file a connect item and if enough upvotes are received we will prioritize accordingly.

**Comment by mkormendy** [comment]
"file a connect item"? How?

**Comment by abhisheksinha89** [comment]
Go to https://connect.microsoft.com/ and under the product category choose SQL Server and then submit feedback. You will need to create an account to login if you don't have one yet.

**Comment by mkormendy** [comment]
I have created the connect item here:
https://connect.microsoft.com/SQLServer/feedback/details/3145097

**Comment by tkopets** [comment]
Thank you @mkormendy!

**Comment by sengokyu** [comment]
Workarround:

```
echo "select 1;" | sqlcmd -S "server" -U "user" -P "password" -i /dev/stdin
```
