### ISSUE TITLE
Install fails on mssql-tools - specified blob doesn't exist

### ISSUE THREAD

**Issue by xenocid** [Microsoft/homebrew-mssql-release#22]
As per documentation, added additional tap and successfully installed `msodbcsql17`, however, attempt to install `mssql-tools` causes the following error:

```
Alexs-MacBook-Pro% brew install --no-sandbox mssql-tools
==> Installing mssql-tools from microsoft/mssql-release
==> Downloading https://sqlchoice.blob.core.windows.net/sqlchoice/17.2.0.1/macOS/mssql-tools-17.2.0.1.tar.gz

curl: (22) The requested URL returned error: 404 The specified blob does not exist.
Error: Failed to download resource "mssql-tools"
Download failed: https://sqlchoice.blob.core.windows.net/sqlchoice/17.2.0.1/macOS/mssql-tools-17.2.0.1.tar.gz
```

**Comment by sweeneypng** [comment]
I got the same problem earlier. The correct url is in Formula/mssql-tools@17.2.0.1.rb, and the correct SHA256 hash is in Formula/mssql-tools.rb. You can edit the files on your machine if you need it working now.

I made pull request #21 to fix this, hopefully will be resolved soon.

**Comment by David-Engel** [comment]
#21 is merged. Thanks! And sorry about that!
