### ISSUE TITLE
Update install instructions (--no-sandbox is an invalid option)

### ISSUE THREAD

**Issue by davidjb** [Microsoft/homebrew-mssql-release#29]
The install instructions at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#os-x-1011-el-capitan-and-macos-1012-sierra feature the command:

```bash
brew install --no-sandbox msodbcsql@13.1.9.2 mssql-tools@14.0.6.0
```
which fails because `--no-sandbox` isn't an option that `brew install` takes.

```bash
Usage: brew install [options] formula
[...options and usage text...]
Error: invalid option: --no-sandbox
```

The install succeeds fine when `brew install` is called just as is so the solution is just to remove this option.

There was the general [all-options-removed](https://github.com/Homebrew/homebrew-core/issues/31510) change to Homebrew which affected all formulae, so I presume removing options relating to sandboxing were caught up in that too.  See also https://discourse.brew.sh/t/since-homebrew-2-0-0-install-params-always-give-invalid-option/4075

**Comment by v-chojas** [comment]
The documentation was changed to remove --no-sandbox.

**Comment by David-Engel** [comment]
Looks like it was only removed for v17. I submitted a PR to remove it for v13, too.

**Comment by David-Engel** [comment]
The doc has been updated now.

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#os-x-1011-el-capitan-and-macos-1012-sierra

Closing this issue.

**Comment by andymcarter** [comment]
I found this solution, but the '--no-sandbox' option is still included on this page:

https://www.microsoft.com/en-us/sql-server/developer-get-started/python/mac/

**Comment by jacks0n** [comment]
It's also included on this page:

https://www.microsoft.com/en-us/sql-server/developer-get-started/node/mac

**Comment by arkadit** [comment]
Our team doesn't maintain Node.js documentation, if you look to to the
installation manual for the ODBC driver you won't see --no-sandbox option.

Thanks,
Arkadi

**Comment by David-Engel** [comment]
@jacks0n Thanks. That reminds me I need to find someone to merge my months old PR which fixes that reference. :)

**Comment by v-mabarw** [comment]
And yeah I saw this just as I sent that other email 😊

Thanks,
Marie

**Comment by geeyan** [comment]
It's also included on this page:

https://www.microsoft.com/en-us/sql-server/developer-get-started/php/mac

**Comment by hanhanhan** [comment]
It's also included here:
https://cloudblogs.microsoft.com/sqlserver/2017/05/16/sql-server-command-line-tools-for-macos-released/

Which was the top result for me when I searched for `homebrew sqlcmd`
