### ISSUE TITLE
Where does BCP find the driver?

### ISSUE THREAD

**Issue by number-cruncher** [microsoft/homebrew-mssql-release#35]
I installed mssql-tools (https://cloudblogs.microsoft.com/sqlserver/2017/05/16/sql-server-command-line-tools-for-macos-released/).  sqlcmd works.  however bcp throws the following error on mac. Unable to locate driver dynamic library. BCP cannot continue.  Where does BCP look for the driver library?

**Comment by number-cruncher** [comment]
Solved it by installing MSSQL 17 (13 didn't work) then updating the odbc.ini and odbcinst.ini files.
odbc.ini 
[MSSQL]
Description = Warehouse
Driver = ODBC Driver 17 for SQL Server
Server = tcp:serverip,1433

odbcinst.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.17.dylib
Setup=/usr/local/lib/libmsodbcsql.17.dylib
UsageCount=1

**Comment by calmitchell617** [comment]
Thank you for posting how you solved the problem, this worked for me as well.

**Comment by trifangrobert** [comment]
I tried reinstalling and it didn't work for me. I had to manually unset $ODBCSYSINI environment variable as well.
