### ISSUE TITLE
Problem with macOs 10.15

### ISSUE THREAD

**Issue by bhupalasuresh** [microsoft/homebrew-mssql-release#37]
Hi, I have upgraded my macBook Pro to Catalina(10.15), from there onwards sql drivers not working properly.

I am using
- CodeIgnitor 3.1.1 framework
- PHP 7.3.10

Fatal error: sqlsrv_fetch_array: Unknown exception caught. in /Users/bhupalasuresh/Sites/sqlconnect/system/database/drivers/sqlsrv/sqlsrv_result.php on line 175

**Comment by yitam** [comment]
hi, @bhupalasuresh, the sqlsrv driver does not yet officially support Catalina. That being said, this issue does not give us enough details to troubleshoot. For example, what was the OS before your upgrade? Did you run `pecl install sqlsrv`? Which version? etc. etc.

Please create a new issue in [msphpsql](https://github.com/Microsoft/msphpsql) by providing more details, repro scripts, etc.

**Comment by bhupalasuresh** [comment]
I have upgraded from Mojave.
I tried by reinstalling all (PHP 7.3.10, apache, sqlsrv and pdo_sqlsrv using brew).

**Comment by yitam** [comment]
@bhupalasuresh did all the re-installation succeed? Did you [reinstall ODBC driver and tools](https://docs.microsoft.com/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#macos)

**Comment by giordyb** [comment]
I have a similar issue with a fresh install of Catalina, when I run
 `isql -v -k "driver={ODBC Driver 17 for SQL Server};server=localhost;PORT=1433;database=test;uid=sa;pwd=P@ssw0rd;"`

i get this error:

`[08001][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]
[08001][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
[01S00][Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute
[ISQL]ERROR: Could not SQLDriverConnect`

if I use the freetds driver
`isql -v -k "driver=/usr/local/lib/libtdsodbc.so;server=localhost;PORT=1433;database=test;uid=sa;pwd=P@ssw0rd" `
it connects

**Comment by yitam** [comment]
@giordyb the error message is clear. OpenSSL is required. Please do `brew install openssl`

**Comment by v-makouz** [comment]
@giordyb On macOS default OpenSSL is 0.9.8, which the driver can not use, but in theory brew should install a newer version, when installing the driver. You can check `ls -l /usr/local/Cellar/openssl*` to see what versions of OpenSSL have been installed by brew (if any). 

If that list proper versions then there maybe some issues with library paths or symlinks

**Comment by giordyb** [comment]
sorry I forgot to mention that I already installed SSL from homebrew:

```
# brew list openssl
/usr/local/Cellar/openssl@1.1/1.1.1d/.bottle/etc/ (7 files)
/usr/local/Cellar/openssl@1.1/1.1.1d/bin/c_rehash
/usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl
/usr/local/Cellar/openssl@1.1/1.1.1d/include/openssl/ (104 files)
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.1.1.dylib
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/libssl.1.1.dylib
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1/ (2 files)
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/ (4 other files)
/usr/local/Cellar/openssl@1.1/1.1.1d/share/doc/ (3926 files)
/usr/local/Cellar/openssl@1.1/1.1.1d/share/man/ (3926 files)
```

**Comment by v-makouz** [comment]
@giordyb Can you run isql with dylib tracing? 
`DYLD_PRINT_LIBRARIES=1 isql -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=...;UID=...;PWD=..."`
To see what it's trying to do

**Comment by ronisbr** [comment]
I am having a problem is the v13 because it seems to need openSSL 1.0 and home-brew now has 1.1. Then I get many errors. The v17, on the other hand, is working fine. Maybe trying to relink everything in openSSL?

**Comment by v-makouz** [comment]
@ronisbr v13 is linked with OpenSSL 1.0, so it won't work unless that's installed, v17 starting with 17.4 dynamically loads OpenSSL and thus can handle multiple versions (1.0 and 1.1 specifically)

More info here:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-ver15#bkmk-openssl

**Comment by giordyb** [comment]
> @giordyb Can you run isql with dylib tracing?
> `DYLD_PRINT_LIBRARIES=1 isql -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=...;UID=...;PWD=..."`
> To see what it's trying to do

here you go:
dyld: loaded: <EDA0F15B-81AB-3824-BFBD-C3E3D3DC3E5C> /usr/local/bin/isql
dyld: loaded: <2A8C10C4-8183-3BCC-93B8-1A8D5B9058F2> /usr/local/Cellar/unixodbc/2.3.7/lib/libodbc.2.dylib
dyld: loaded: <278EA021-ECE6-3B96-A705-53751D486E7A> /usr/local/opt/libtool/lib/libltdl.7.dylib
dyld: loaded: <EB71AC8F-EA44-3BEE-A210-2D92251CA51D> /usr/lib/libiconv.2.dylib
dyld: loaded: <3F6EC784-2FC8-3E33-A035-D45508853E1E> /usr/lib/libedit.3.dylib
dyld: loaded: <1DD1BCD2-2C85-3B81-8CAF-224FB042F441> /usr/lib/libSystem.B.dylib
dyld: loaded: <74F6459D-3606-3ADB-9808-F6B0FE70062D> /usr/lib/system/libcache.dylib
dyld: loaded: <1333752F-5117-3E86-803A-06E166D80C8C> /usr/lib/system/libcommonCrypto.dylib
dyld: loaded: <0437EBEF-8191-3912-A365-D6BB75C7A810> /usr/lib/system/libcompiler_rt.dylib
dyld: loaded: <7FAF372E-BAD5-30E6-A8F2-A3D06B91DC80> /usr/lib/system/libcopyfile.dylib
dyld: loaded: <AE25C9EE-5D63-3E49-B3AA-D482D35C085A> /usr/lib/system/libcorecrypto.dylib
dyld: loaded: <1FF421B6-4BF0-3B5F-8F56-5ED3B3EFE06F> /usr/lib/system/libdispatch.dylib
dyld: loaded: <2FA4B359-624B-337C-9207-CDCF841C2E52> /usr/lib/system/libdyld.dylib
dyld: loaded: <7EEF9246-30B4-34DD-8AD6-79679D1A7784> /usr/lib/system/libkeymgr.dylib
dyld: loaded: <CC02D5B3-A95D-3B16-8EE5-D62521CFE899> /usr/lib/system/liblaunch.dylib
dyld: loaded: <6C3E49B2-594D-3B9D-82DB-C4ABEB9788AB> /usr/lib/system/libmacho.dylib
dyld: loaded: <A1BCAA32-A194-3DBE-9930-8F49A4AEF284> /usr/lib/system/libquarantine.dylib
dyld: loaded: <DD7AE862-F179-3C07-A4FC-5775DDD4D3E6> /usr/lib/system/libremovefile.dylib
dyld: loaded: <ECE44856-D279-3B5D-A0AA-8BE421D200C4> /usr/lib/system/libsystem_asl.dylib
dyld: loaded: <DC521115-905A-3A0D-9337-C55FACCEA85F> /usr/lib/system/libsystem_blocks.dylib
dyld: loaded: <5AD50779-955E-3F56-BCB9-1E14833B3455> /usr/lib/system/libsystem_c.dylib
dyld: loaded: <7A2329E0-3C84-3DB7-BC32-E7796C50D621> /usr/lib/system/libsystem_configuration.dylib
dyld: loaded: <DF341577-A307-3722-BB24-D4AACEAB19B3> /usr/lib/system/libsystem_coreservices.dylib
dyld: loaded: <E862B5B1-A367-39CA-8319-B2F9DFADF606> /usr/lib/system/libsystem_darwin.dylib
dyld: loaded: <2A9C6F3E-427B-332E-BDD3-D4651306F3DE> /usr/lib/system/libsystem_dnssd.dylib
dyld: loaded: <B94C0052-B75A-3169-80AA-5F480588AF6E> /usr/lib/system/libsystem_featureflags.dylib
dyld: loaded: <18CC56C5-5325-3375-BF99-FAE7F4F19DDD> /usr/lib/system/libsystem_info.dylib
dyld: loaded: <636A1A1C-7AFC-3E82-B86B-0173912A3437> /usr/lib/system/libsystem_m.dylib
dyld: loaded: <F82A587B-44A2-3699-A218-9D3ECEE23D5A> /usr/lib/system/libsystem_malloc.dylib
dyld: loaded: <7F206A43-A941-3BAB-AE3A-16169F2FE6AB> /usr/lib/system/libsystem_networkextension.dylib
dyld: loaded: <C95CC58E-35E7-3828-AA2A-6EED73C12DE5> /usr/lib/system/libsystem_notify.dylib
dyld: loaded: <2183D15E-2CFD-3160-80CE-A948F0529005> /usr/lib/system/libsystem_sandbox.dylib
dyld: loaded: <D2782294-ACDC-30FF-A794-B4C1B324526B> /usr/lib/system/libsystem_secinit.dylib
dyld: loaded: <18918E9C-45BC-3D5A-A6B6-3DBC60EEE2E1> /usr/lib/system/libsystem_kernel.dylib
dyld: loaded: <0CCDD81F-0891-3400-8A97-6CAC3BBBE2F9> /usr/lib/system/libsystem_platform.dylib
dyld: loaded: <53C65598-9E9E-36FF-BDC2-74F228E58C5C> /usr/lib/system/libsystem_pthread.dylib
dyld: loaded: <A44E4405-E22E-32E9-83DE-8C7A82401DA0> /usr/lib/system/libsystem_symptoms.dylib
dyld: loaded: <376CC435-E656-37D9-A5FF-C49B6E4525E2> /usr/lib/system/libsystem_trace.dylib
dyld: loaded: <44448F1F-08E5-3425-ADBA-C38A9E8F90C7> /usr/lib/system/libunwind.dylib
dyld: loaded: <99CC9436-D653-3762-ADBB-9054EBD1BA2B> /usr/lib/system/libxpc.dylib
dyld: loaded: <D866A31E-5CB1-3327-8D22-C4F83C9225D0> /usr/lib/libobjc.A.dylib
dyld: loaded: <D89ABFBF-3754-35AB-BAEE-FBF14857F79B> /usr/lib/libc++abi.dylib
dyld: loaded: <1D42387D-206A-3F06-9B5F-705B83EAC295> /usr/lib/libc++.1.dylib
dyld: loaded: <EC5B95D9-388B-3351-9192-CD6CDB8C3E0F> /usr/lib/libcharset.1.dylib
dyld: loaded: <7115BD9E-9A53-3538-BA7C-6D71E8C0F9F1> /usr/lib/libncurses.5.4.dylib
dyld: loaded: <B4E1583D-ABC0-3678-B9FE-7DF6711FB87F> /usr/local/lib/libmsodbcsql.17.dylib
dyld: loaded: <15D61616-B29B-3BDB-8624-4B84A4956485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
dyld: loaded: <FAC4A398-81C2-370C-B543-208F3942E75E> /usr/local/lib/libodbcinst.2.dylib
dyld: loaded: <8018F664-0026-3CC3-8685-3E2FE0BF2C7F> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
dyld: loaded: <528A0ABE-B583-3DA1-8E5B-9CA7E89303DE> /usr/lib/libfakelink.dylib
dyld: loaded: <83F42398-DB41-3BB2-B8A1-10D78C4B5778> /usr/lib/libDiagnosticMessagesClient.dylib
dyld: loaded: <4CBF52D7-7235-34C8-9FF1-8657076B604F> /usr/lib/libicucore.A.dylib
dyld: loaded: <3EC7A143-AF2D-35EE-9C08-542B2907E3D2> /usr/lib/libz.1.dylib
dyld: loaded: <735D30D6-8713-382B-97EA-12EFCC053486> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
dyld: loaded: <FB3774D5-C940-35FB-960A-86253A01BDAE> /System/Library/Frameworks/Security.framework/Versions/A/Security
dyld: loaded: <A149061D-5893-35B5-AE7F-BA889DFEADB2> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
dyld: loaded: <51DB9CFB-808F-32E8-BB34-39F6702DBDED> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
dyld: loaded: <D8C5B7F0-04D5-3470-A9C4-EF8B2FF96986> /usr/lib/libnetwork.dylib
dyld: loaded: <470C2315-3047-39BB-BB6B-2C620087091C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
dyld: loaded: <6C5102F7-85BE-34E0-BFC7-0569FCAE2755> /usr/lib/libheimdal-asn1.dylib
dyld: loaded: <2D0B1BE5-9B8A-394F-82F7-F612B1A6C73F> /usr/lib/libsqlite3.dylib
dyld: loaded: <34848168-B77D-3749-A7ED-B1F3F92E5162> /usr/lib/libresolv.9.dylib
dyld: loaded: <5EA797F3-2F7A-3E0C-8DBC-DBE145004EC5> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
dyld: loaded: <C4F9F5BD-BA21-3038-9665-4D298FB7511C> /usr/lib/libpcap.A.dylib
dyld: loaded: <FBB4A97B-D7CF-3B8C-932D-672343D63260> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
dyld: loaded: <4F054E37-783A-3FCD-B90B-23A0A83621D9> /usr/lib/libcoretls.dylib
dyld: loaded: <62E31BC8-A823-3816-B130-2BB550433203> /usr/lib/libcoretls_cfhelpers.dylib
dyld: loaded: <9B990E6A-D9EB-3F2C-B7CA-085A47D4BC62> /usr/lib/libapple_nghttp2.dylib
dyld: loaded: <1CE2BD78-F68E-36A3-BCE9-E9EAB78D9FF3> /usr/lib/libenergytrace.dylib
dyld: loaded: <E57A0CC6-226D-3529-A23A-D5DD6674DB3E> /usr/lib/libbsm.0.dylib
dyld: loaded: <F9FF90CE-DCB0-3918-882F-6E475A6E244A> /usr/lib/system/libkxld.dylib
dyld: loaded: <7EEDBF8A-8812-33D6-A5B0-F7D36825EE73> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
dyld: loaded: <02ABA04D-5843-3850-82A3-EBECA6FC2CDF> /usr/lib/libpam.2.dylib
dyld: loaded: <46AAA43E-6FC6-38A8-B696-62143706D33B> /usr/lib/libxar.1.dylib
dyld: loaded: <F4B3519A-A4FC-30E0-805C-70C99BA3FDDA> /usr/lib/libauto.dylib
dyld: loaded: <77B35FFD-CE66-3CCA-BEDD-9771D698CEE3> /usr/lib/libcompression.dylib
dyld: loaded: <A3D2B0A0-3C72-3893-87BF-D45FE398A905> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
dyld: loaded: <25C00824-621A-3FF1-9B6C-52999B6DDF4E> /usr/lib/libarchive.2.dylib
dyld: loaded: <0DB777D9-F9A1-3921-BFCE-05A000293915> /usr/lib/libxml2.2.dylib
dyld: loaded: <A52A533D-DA25-3607-A18E-CA7C539E1C52> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
dyld: loaded: <C8F86BE7-AAED-30A6-BBC2-550446137E7C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
dyld: loaded: <DCC4FA36-0563-3BD2-AE35-9BAF52F5BD98> /usr/lib/liblangid.dylib
dyld: loaded: <CDEA70A4-318B-3990-9AAE-1D7B18132760> /usr/lib/libCRFSuite.dylib
dyld: loaded: <7D2522C8-8CBE-32C9-8743-A8F598602F4C> /usr/lib/liblzma.5.dylib
dyld: loaded: <F3D26C17-BC6E-3A83-A3BB-137343C87303> /usr/lib/libbz2.1.0.dylib
dyld: loaded: <9BB76885-7CD7-3369-B759-33F7E5DA5392> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
dyld: loaded: <FAA1467B-6D39-3EBE-9810-A4DF49478F10> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
dyld: loaded: <028AC15A-35B7-3E1F-BCDC-470C8EA0CA09> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
dyld: loaded: <A667F007-A599-3869-99F7-1F8460011015> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
dyld: loaded: <F0A931E4-0C31-36BA-8DD7-01FDF9813FB7> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
dyld: loaded: <3301AF1B-D178-306A-9641-B57AA03FB1BE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
dyld: loaded: <88F59BD5-412A-35EE-AD45-E6BF80B24891> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
dyld: loaded: <C1798F09-36D3-3C8E-AF72-A3DE63962AF1> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
dyld: loaded: <62C3066A-3991-313F-AE2D-75B2B5934D52> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
dyld: loaded: <5C3C3672-2549-316E-9AC6-A1CFDCD16E9C> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
dyld: loaded: <BA114B8C-BE33-3DBB-BDC8-25423DBBD3A3> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
dyld: loaded: <FFE90A0A-BEBC-3032-9368-94C016BE0795> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
dyld: loaded: <87BE8D5C-5D35-3434-8BDF-1615349C7A21> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
dyld: loaded: <329A9840-CBD8-33A2-A584-2805042284A9> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
dyld: loaded: <8957F147-9371-3728-896E-FC517AC7E86E> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
dyld: loaded: <2E84458F-5748-3A9B-94F3-CAF3C79E6383> /usr/lib/libmecabra.dylib
dyld: loaded: <956D070C-B522-3A08-891A-CAD6BA4082D1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
dyld: loaded: <FDA0E623-F6F2-3402-B72C-0C60A32C2CC1> /usr/lib/libmecab.dylib
dyld: loaded: <5E297121-22A7-3A2F-92B9-DD3E5C829CC7> /usr/lib/libgermantok.dylib
dyld: loaded: <22582C9C-3D32-3832-8925-813E4F2BA8DA> /usr/lib/libThaiTokenizer.dylib
dyld: loaded: <4D68248B-BD40-32E3-ABCA-CE23BCA0A6A4> /usr/lib/libChineseTokenizer.dylib
dyld: loaded: <DCF3349F-1159-3F46-81E0-C18E041DC940> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
dyld: loaded: <79C1A1C7-E97A-3B7A-8737-444B402A7AA0> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
dyld: loaded: <18B48679-444E-3680-A9B2-006A8D1DE3EB> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
dyld: loaded: <E849AEB0-2995-38A4-B0C3-4ACEAF434D12> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
dyld: loaded: <B950B953-116A-3C78-91A9-F983F61BC795> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
dyld: loaded: <5C248B39-F233-3074-A3A5-AF8F436FBF87> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
dyld: loaded: <3AEC87AB-568C-3D88-959A-D6D8C2776FEC> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
dyld: loaded: <4536B3F7-7017-36F5-B500-1A63F691CE03> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
dyld: loaded: <7EE59014-8FC5-3369-868B-8A87E590BF78> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
dyld: loaded: <BAE2A5E4-14A1-3C54-86DF-888FA26C745E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
dyld: loaded: <093F97A4-47DE-38DF-BB7A-FF5A3FB0BB3B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
dyld: loaded: <D3478ED9-A757-355F-A4A0-464E133182D6> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
dyld: loaded: <8D1CA277-C4F7-3F3B-919E-73B68D39535E> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
dyld: loaded: <23AF4473-4FDB-39D9-8862-7D23276606A9> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
dyld: loaded: <94910CCB-C386-3912-84A2-1A730BB6EF62> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
dyld: loaded: <49C8E101-945E-369B-91D3-2129000DFF35> /usr/lib/libcmph.dylib
dyld: loaded: <AA81FC34-A7F6-3DA2-A275-B34F75099C7B> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
dyld: loaded: <ECFA2FFB-D5B6-3916-96F7-9F3A1EB1E534> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
dyld: loaded: <0319F563-43AE-3F80-9107-7F0056E726DB> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
dyld: loaded: <6482C994-4DB4-320D-8FD4-50C998EA8856> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
dyld: loaded: <B88D4C21-DAEF-3566-8EAE-5973C51A16FD> /usr/lib/libutil.dylib
dyld: loaded: <792520D2-5D81-3867-8DC7-75F8205D5A5B> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
dyld: loaded: <2B80E13A-AFFC-355A-AA82-CCDEF4718E66> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
dyld: loaded: <5E2B9000-49D6-3BFA-97F1-3B47A8A7418D> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
dyld: loaded: <C30A840F-E7E7-39D5-A633-9C256650B552> /usr/lib/libxslt.1.dylib
dyld: loaded: <1D04F654-22B1-37EF-90AD-3ADB5238806A> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
[08001][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]
[08001][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
[01S00][Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute

**Comment by v-makouz** [comment]
@giordyb It looks like the problem here is that the ODBC Driver 17 came out before Catalina and specifically before there was OpenSSL 1.1 on the Mac, so it was never tested with that, as such the Mac driver will only try to load various OpenSSL 1.0 versions. Unfortunately the documentation and the error message don't make that distinction between Linux and Mac.

In any case for now I would recommend installing OpenSSL 1.0

**Comment by v-makouz** [comment]
@giordyb Further testing indicates that on many Machines the driver actually works OK with OpenSSL 1.1 (just untested on the Mac), can you check `ls -l /usr/local/opt/openssl/lib/libssl.dylib` ?

**Comment by v-chojas** [comment]
You can also `ls -l /usr/local/opt/openssl/lib` to see what libraries are actually available in the OpenSSL directory

**Comment by v-chojas** [comment]
I have installed driver using commands from the documentation on a clean 10.15 VM and had no problems connecting, despite the fact that brew installed OpenSSL 1.1.1d.

**Comment by giordyb** [comment]
> @giordyb Further testing indicates that on many Machines the driver actually works OK with OpenSSL 1.1 (just untested on the Mac), can you check `ls -l /usr/local/opt/openssl/lib/libssl.dylib` ?

Hi, 
i was missing the /usr/local/opt/openssl/lib folder altogether, once I create a symlink to openssl@1.1 it started working, thanks!

**Comment by mattiasarro** [comment]
thanks @giordyb that solved it for me as well:

```
ln -s /usr/local/Cellar/openssl@1.1/1.1.1g /usr/local/opt/openssl
```

**Comment by erfannariman** [comment]
Running into the same issue right now. When I run `DYLD_PRINT_LIBRARIES=1 isql -v -k "<connection string"` I get:

```
dyld: loaded:  /usr/local/opt/openssl/lib/libssl.dylib
dyld: loaded: /usr/local/Cellar/openssl@3/3.0.0/lib/libcrypto.3.dylib
[08001][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]
[08001][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
[ISQL]ERROR: Could not SQLDriverConnect
```

It looks like it's still grabbing the wrong `libcrypto.3.dylib`, any idea how I can solve this?

I already did `ln -s /usr/local/Cellar/openssl@1.1/1.1.1l_1 /usr/local/opt/openssl  `

**Comment by erfannariman** [comment]
> ln -s /usr/local/Cellar/openssl@1.1/1.1.1l_1 /usr/local/opt/openssl

This worked, thanks.

**Comment by dfx413** [comment]
Wow, you saved me hours of trial and error. Thank you!

**Comment by dragnblow** [comment]
1. When I ran - brew info openssl
￼

2. More info - lrwxr-xr-x (all of these)
￼

3. The ERROR
￼

4. Unixodbc
￼

**Comment by dragnblow** [comment]
1. brew info openssl

<img width="545" alt="Cryptography and SSLTLS Toolkit" src="https://user-images.githubusercontent.com/94332384/147835336-cbccdee9-99d8-4a4f-b6d5-942857ab36cc.png">

2. all these are lrwxr-xr-x
<img width="523" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/94332384/147835348-08901227-611f-4db2-b8a2-06d17acc6240.png">

3. The ERROR
<img width="1006" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/94332384/147835366-4813f922-3abc-4c39-8ce9-b8707d2768f1.png">

4. Unixodbc
<img width="546" alt="Conflicts with" src="https://user-images.githubusercontent.com/94332384/147835373-d6685526-b8a7-44e0-be12-e605c83f51d1.png">

5. MSSQLODBC
![image](https://user-images.githubusercontent.com/94332384/147835437-07c44677-7928-4ca6-b663-897abc7b063a.png)

Can any of you please help me on this? I cannot connect to sql server from isql and python (jupyter notebook). Thank you!

**Comment by David-Engel** [comment]
@dragnblow From your screenshots, it looks like you are hitting the problem that the driver doesn't yet support OpenSSL 3.0, yet brew has replaced it as the default version. The fix is to ensure OpenSSL 1.1 is installed and that the openssl "default" is linked to version 1.1. See this comment for details: https://github.com/microsoft/homebrew-mssql-release/issues/59#issuecomment-997284653

**Comment by dragnblow** [comment]
Thank you David! 

My which OpenSSL points to the one from anaconda navigator (/opt/anaconda3/bin/OpenSSL) and my pyodbc.drivers() returns the value "ODBC Driver 17 for sql server" 

Do you think OpenSSL is causing the issue here? 

Also, the error I now get is the 08001 - client unable to establish a connection! 

I sincerely appreciate any help here! 

Apologize the delay in responding!

**Comment by David-Engel** [comment]
@dragnblow If the error right before that still says "OpenSSL library could not be loaded, ...", OpenSSL would be my bet. If the comments in the other issue don't resolve it for you, I'd comment there instead. Comments on a closed issue are easily missed.

**Comment by dragnblow** [comment]
@David-Engel - please comment there, yes! Hope I will
Get notified, don't want to miss any help :( 

I get the error 08001 both using isql(terminal) and my Python connection string (pyodbc).

**Comment by David-Engel** [comment]
> @David-Engel - please comment there, yes! Hope I will Get notified, don't want to miss any help :(
> 
> I get the error 08001 both using isql(terminal) and my Python connection string (pyodbc).

@dragnblow I meant for _you_ to comment there with your details. Be sure to include all errors, not just the final 08001 error.

**Comment by jontingvold** [comment]
For MacOS Monterey 12.2 on Apple Scilicon (M1) the following works for me:
```ln -sfn /opt/homebrew/Cellar/openssl@1.1/1.1.1m /opt/homebrew/opt/openssl```.
Note that you need to change `1.1.1m` to your current version if you use a different version.
