### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by dakcarto** [Microsoft/homebrew-mssql-release#4]
Hi,

Looking to redistribute `msodbcsql` (for free) inside a software stack built with this Homebrew tap. However, the applicable license restricts distribution of the software to non-Windows platforms:

```
2.	ADDITIONAL LICENSING REQUIREMENTS AND/OR USE RIGHTS.
a.	Distributable Code.
...
iii.	Distribution Restrictions. You may not
...
•	distribute Distributable Code to run on a platform other than the Windows platform;
```
That wording seems to even negate distribution via this Homebrew tap.

Please advise whether this license can be changed, or another may be used. Feel free to contact me directly.

`msodbcsql` license attached for reference: [LICENSE.txt](https://github.com/Microsoft/homebrew-mssql-release/files/1443601/LICENSE.txt)

**Comment by David-Engel** [comment]
@dakcarto Thanks for catching that. It definitely seems like a mistake. I'm looking into getting it updated.

**Comment by David-Engel** [comment]
@dakcarto FYI, we've updated the license and that restriction has been removed.

Regards,
David
