### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by aNullValue** [microsoft/homebrew-mssql-release#41]
I've attempted to install msodbcsql17 unattended, but it fails and kills the installation job:

```
Do you accept the license terms? (Enter YES or NO)
Error: An exception occurred within a child process:
  NoMethodError: undefined method `chomp' for nil:NilClass
```

The first time it failed, I looked at the brew formula and thought that I had taken care of it by additionally providing environment variable ACCEPT_EULA=Y. As I'm sure you're aware (though I wasn't), brew now additionally requires HOMEBREW_NO_ENV_FILTERING=1 in order for that to work.

The doc at [Installing the Microsoft ODBC Driver for SQL Server on Linux and macOS](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15) amusingly provides examples for Linux that include ACCEPT_EULA=Y, but the MacOS example does not. Could the docs be changed such that the examples have parity between platforms? For example, MacOS could become "HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 mssql-tools". 

Or, failing that, could the brew formula be changed so that it makes reference to the need for HOMEBREW_NO_ENV_FILTERING=1? Or, failing that, a link to [this](https://github.com/microsoft/homebrew-mssql-release/issues/8#issuecomment-351110740) comment would be helpful to others needing to do this in the future. :) 

<edit>

Oh, and I forgot to initially mention it, but your error handling for the session not being interactive appears not to work, given the quoted error output above.

**Comment by David-Engel** [comment]
@aNullValue Thanks for the suggestion. We’ve been considering a variable change to get rid of the need for the HOMEBREW_NO_ENV_FILTERING variable and updating the docs. At the least, the docs will be updated later this month.

Thanks,
David
