### ISSUE TITLE
Issue installing on MacOS

### ISSUE THREAD

**Issue by nbrow** [microsoft/homebrew-mssql-release#42]
Tried to install in the Terminal but Home Brew doesn't seem to have a msodbcsql17 formulae to install. I received this message:

(base) Nicholass-MacBook-Pro:~ Nick$ Error: No available formula with the name "msodbcsql17" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by v-chojas** [comment]
Did you run these commands first?
```
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
```
...then try to install `msodbcsql17`, if you are still seeing errors then please post transcript of entire terminal session for further assistance.

**Comment by nbrow** [comment]
I was able to install but my system does not find the OBDC when I try to open. Is there a configuration or setup necessary are installing?

**Comment by v-chojas** [comment]
I am not sure what you mean by "does not find the OBDC when I try to open". Could you explain more about what you are trying to do?

**Comment by nbrow** [comment]
Sure, I'm looking to get access to a MS Database in Open Office. When I go to select an ODBC, nothing is available. 
<img width="1020" alt="Screen Shot 2020-03-20 at 11 27 10 AM" src="https://user-images.githubusercontent.com/42661884/77182569-59fa2280-6aa3-11ea-9690-82deb1862be5.png">

**Comment by v-chojas** [comment]
You need to create a DSN first. Run `odbcinst -j` to find the location of the `odbc.ini` file, then add a DSN entry to it.

 See http://www.unixodbc.org/odbcinst.html for more information.

**Comment by nbrow** [comment]
Here was the output: 

(base) Nicholass-MacBook-Pro:~ Nick$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /Users/Nick/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by nbrow** [comment]
I'm not sure how to add a DSN entry.

**Comment by v-chojas** [comment]
See http://www.unixodbc.org/odbcinst.html and https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute
