### ISSUE TITLE
Issue with installation on MacOS Mojave

### ISSUE THREAD

**Issue by 1rosehip** [microsoft/homebrew-mssql-release#43]
Hello,
I'm trying to install and get the following errors:
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release

-e:1:in `<main>': undefined method `canonical_segments' for #<Gem::Version "2.3.7"> (NoMethodError)
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3.mavericks.bottle.tar.gz
Already downloaded: /Users/miriam/Library/Caches/Homebrew/portable-ruby-2.6.3.mavericks.bottle.tar.gz
perl version 5.26.1 can't run /usr/bin/shasum.  Try the alternative(s):

/usr/bin/shasum5.18 (uses perl 5.18)

Run "man perl" for more information about multiple version support in
Mac OS X.
Error: Checksum mismatch.
Expected: ab81211a2052ccaa6d050741c433b728d0641523d8742eef23a5b450811e5104
  Actual: 
 Archive: /Users/miriam/Library/Caches/Homebrew/portable-ruby-2.6.3.mavericks.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.

Could you please advise?

**Comment by v-chojas** [comment]
That looks like a Homebrew issue. The error message suggests it can't hash the file, how about renaming /usr/bin/shasum and then symlinking /usr/bin/shasum to /usr/bin/shasum5.18 as the message seems to imply?

**Comment by 1rosehip** [comment]
Is there a way to install command line sql without homebrew? I'm not able to resolve the issue above easily.

**Comment by v-chojas** [comment]
You can read the formulae in this repo to find the download links, and extract the files to the specified locations.
Note that you will need to find and install the dependencies manually too.

**Comment by 1rosehip** [comment]
Thank you
