### ISSUE TITLE
sqlcmd won't work with DSN, isql does

### ISSUE THREAD

**Issue by sterlingpetersen** [microsoft/homebrew-mssql-release#44]
This one is leaving me baffled. I have a DSN configured for a server I call `prod`.

`sqlcmd -D myproductionserverfullyspecified` works just fine.

`isql prod` works just fine.

`sqlcmd -D -S prod` does not and throws the following:

`Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..`

Not sure where the disconnect is here, as `isql` seems to be picking up the DSN configuration just fine.

Any ideas? Bug? Feature? Misconfiguration?

**Comment by v-chojas** [comment]
Could you write out the whole commands and DSNs that you used? You can replace information with placeholders if you do not want to disclose.

**Comment by sterlingpetersen** [comment]
For the record, I'm using "Integrated Authentication", if that makes a difference.

Let me know if you were looking for something more. This isn't a showstopper for me—I can clearly just use the server path instead of the DSN for `sqlcmd`, just thought it was bizarre that it seems to work everywhere else.

odbcinst.ini
```
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.17.dylib
UsageCount=8
```

odbc.ini
```
[prod]
Driver = ODBC Driver 17 for SQL Server
Server = prod.xxxx.xxxx.xxxx.xxx
Trusted_Connection = yes
```

Doesn't Work
------------
`sqlcmd -D -S prod`

Works
-----
`sqlcmd -S prod.xxxx.xxxx.xxxx.xxx`

Works
-----
`isql prod`

Works
-----
Note: Requires csvkit, mssql, pyodbc
`sql2csv --db "mssql+pyodbc://prod" --query "select top 10 * from MyDataWarehouse.dbo.CustomTestTable"`

**Comment by v-chojas** [comment]
Thank you for the details, I have confirmed this is a bug in the sqlcmd and will try to have it fixed in the next version.

**Comment by frankrutz** [comment]
Probably same problem here. But no workaround, our system heavily depends on DSN usage in DB-automation.

Our DSN entry is mssql-ee     which points in odbc.ini to mssql-ee.mydomain.com

Centos8.  **sqlcmd Version 17.5.0002.1 Linux**
```

potf@RHEL8:VWSServer:/users/potf $ /usr/bin/odbcinst  -j   
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /users/potf/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

Running sqlcmd on the (pingable) server mssql-ee is OK:

```
potf@RHEL8:VWSServer:/users/potf $ sqlcmd -S  mssql-ee -U username -P password -Q "select getDate();"
                       
-----------------------
2020-07-07 20:45:49.390
(1 rows affected
```

Running sqlcmd on the DSN of the same server mssql_ee (watch the underscore) is not OK:
```
potf@RHEL8:VWSServer:/users/potf $ sqlcmd -D -S mssql_ee -U username -P password -Q "select getDate();"
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```

On an older version, but with RHEL7, Version 17.4.0001.1 Linux , DSN was working fine.
Let me know if I can help.

**Comment by v-chojas** [comment]
It will be fixed in the next version of sqlcmd, in the meantime please continue to use 17.4.1.1 .

**Comment by frankrutz** [comment]
Reverted to 17.4.0001.1 , works fine. Thanks!

```
potf@RHEL8::/users/potf $ sqlcmd -U user -P password -D -S mssql_ee -Q "select getDate()"
                       
-----------------------
2020-07-08 11:37:58.450

(1 rows affected)
potf@RHEL8::/users/potf $ sqlcmd -? | grep Version
Version 17.4.0001.1 Linux
```

**Comment by v-chojas** [comment]
17.6 has been released and contains the fix.

**Comment by cambob1** [comment]
Worked for me as well.
Many thanks.
