### ISSUE TITLE
Why is 'caveat' required?

### ISSUE THREAD

**Issue by MikeB2019x** [microsoft/homebrew-mssql-release#47]
This extract from the installation 'formula' below is confusing.  My question is what is a formula 'uninstall'?  The formula doesn't include an 'uninstall' method and the 'caveat' suggests using the same uninstall command as the 'install' method.  So won't the former always fail because the 'install' method has already taken the action suggested by the 'caveat' ?

```
  def install
    return false unless check_eula_acceptance?

    chmod 0444, "lib/libmsodbcsql.17.dylib"
    chmod 0444, "share/msodbcsql17/resources/en_US/msodbcsqlr17.rll"
    chmod 0644, "include/msodbcsql17/msodbcsql.h"
    chmod 0644, "odbcinst.ini"
    chmod 0644, "share/doc/msodbcsql17/LICENSE.txt"
    chmod 0644, "share/doc/msodbcsql17/RELEASE_NOTES"

    cp_r ".", prefix.to_s

    if build.with? "registration"
      system "odbcinst", "-u", "-d", "-n", "\"ODBC Driver 17 for SQL Server\"".  <=========
      system "odbcinst", "-i", "-d", "-f", "./odbcinst.ini"
    end
  end

  def caveats; <<~EOS
    If you installed this formula with the registration option (default), you'll
    need to manually remove [ODBC Driver 17 for SQL Server] section from
    odbcinst.ini after the formula is uninstalled. This can be done by executing
    the following command:
        odbcinst -u -d -n "ODBC Driver 17 for SQL Server" <=========
    EOS
  end
```

**Comment by v-chojas** [comment]
It always attempts to remove the previous version before installing the current one.

**Comment by MikeB2019x** [comment]
Right.  So two thoughts come to mind:

1. if the clean up matters could it be built in to the 'uninstall'
2. if the clean up doesn't matter, then a new 'install' will take care of everything anyways.

The caveat makes it seem like something should be done 'now' because it's right there above the prompt.  Which makes no sense when actually it's something that only needs to be done in the future, at which time nobody will remember the caveat, right?

**Comment by v-chojas** [comment]
It is just an informational message.
