### ISSUE TITLE
Create a Wiki that Points to or states the macOS installation solutions

### ISSUE THREAD

**Issue by MikeB2019x** [microsoft/homebrew-mssql-release#48]
It looks like there are a lot of problems with the macOS installation.  The problems go as far back as version 13 of ODBC install.  The solution for driver 'file not found' is that the files are placed in an unexpected directory.  The solution is a symbolic link pointing the installer to where the files are actually located.  The substance of that solution is outlined at this StackOverflow [question/answer](https://stackoverflow.com/questions/44527452/cant-open-lib-odbc-driver-13-for-sql-server-sym-linking-issue?rq=1).  I suggest:

1. a wiki created here outlining the solution and/or
2. the official [MS installation page for macOS](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15) also make mention that as a final step the creation of symbolic links and finally
3. the wiki and/or MS installation page should explicitly include a statement of what files (it does) were installed and **_WHERE_** they are installed.  That way at least a user can tell if the installation executed properly.

**Comment by v-chojas** [comment]
Try installing in a _clean_ environment (immediately after installing OS, and Homebrew) before making any broad claims about the driver. All the past issues appear to be from those who have modified their environment, accidentally or otherwise, in an undesirable way.

**Comment by MikeB2019x** [comment]
Thank you for your reply.  My suggestion is you could save some trouble by having a wiki.  If you document found solutions and what the end state should look like, that will avoid a lot of unnecessary issues being raised.
 
That said, I was in a clean environment ie. I had to change to a new laptop.  Everything had to be reinstalled and I followed instructions to the letter.  BUT the symlink ended up being the correct answer for me (and others it turns out).

Let me emphasize, I am not blaming the driver.  The driver is fine but the installation appears to be missing a final step though I don't know if that step can be built in to the installation 'formula'.  And documenting a process is always a good thing: 'Do this. The following happens.  End result should look like this.'

**Comment by v-chojas** [comment]
You can already see what is installed if you look at the formula in this repo.

Did you install anything else besides OS and Homebrew before installing the driver? If so, then that was not a clean environment.

I just started a clean VM with Catalina, ran the commands listed at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15 , and it installed successfully and worked. There is no "missing final step".
