### ISSUE TITLE
Error: Non-symlink alias

### ISSUE THREAD

**Issue by rose-is-a-rose** [microsoft/homebrew-mssql-release#50]
Getting ` Non-symlink alias` errors when tapping this repo 

![Screen Shot 2020-08-12 at 11 21 03](https://user-images.githubusercontent.com/11881403/90033876-f230b800-dc8d-11ea-8768-cb5f058e9165.png)

**Comment by v-chojas** [comment]
What OS version are you using? I do not see this error.

**Comment by rose-is-a-rose** [comment]
Resolved, related to the symlink config in git.
