### ISSUE TITLE
Redistributable?

### ISSUE THREAD

**Issue by rcoup** [microsoft/homebrew-mssql-release#57]
Is the Microsoft ODBC driver 17 for SQL Server on macOS (& Linux) redistributable? The license file mentions distributing:

```
2. DISTRIBUTABLE CODE. The software may contain code you are permitted to
   distribute (i.e. make available for third parties) in applications you develop,
   as described in this Section.

   a) Distribution Rights. The code and test files described below are
      distributable if included with the software.

      i. REDIST.TXT Files. You may copy and distribute the object code form
         of code listed on the REDIST list in the software, if any, or listed at REDIST;

      ...
```

But there isn't a `REDIST.TXT` file list.

**Comment by David-Engel** [comment]
Yes, it's redistributabe. The license is mostly boilerplate across products so has some sections that say "may" or "if included". There is no REDIST.TXT file because there are no third party libraries included with the driver.

Regards,
David

**Comment by David-Engel** [comment]
So I just re-read the EULA. I think I was mistaken about what the REDIST.TXT file is for. We got a new one last year that follows newer license templates but I think it was missed that the old and new ones described redistribution differently. The old one talked about redistribution in the context of the entire package. But the new one seems to have added the REDIST.TXT concept for defining which parts of the package are redistributable. I'll reach out to our legal department to see what our options are for adjusting the EULA or if we need to add a REDIST.TXT file to the package to clarify things. Regardless of the outcome, the entire package is intended to be redistributable.

**Comment by David-Engel** [comment]
FYI, the [EULA](https://aka.ms/odbc17eula) has been updated.

```
2. DISTRIBUTABLE CODE. The software may contain code you are permitted to
   distribute (i.e. make available for third parties) in applications you develop,
   as described in this Section. 

   a) Distribution Rights. The code and test files described below are
      distributable if included with the software.

      i. REDIST.TXT Files. You may copy and distribute the object code form
         of code listed on the REDIST list in the software, if any, or listed
         at REDIST (https://aka.ms/odbc17eularedist);
```

The [https://aka.ms/odbc17eularedist link](https://aka.ms/odbc17eularedist) currently says:

```
Distributable Code for the Microsoft ODBC Driver for SQL Server

The entire package may be redistributed.

For the latest version of this REDIST file, please visit https://aka.ms/odbc17eularedist
```

**Comment by rcoup** [comment]
Thanks @David-Engel 😃
