### ISSUE TITLE
brew output download failed

### ISSUE THREAD

**Issue by bpark76** [Microsoft/homebrew-mssql-release#6]
Dear Microsoft,

This is message I got.

`Byungkyus-Mac-Pro:~ bpark$ brew install --without-registration msodbcsql`
`Updating Homebrew...`
`==> Auto-updated Homebrew!`
`Updated 1 tap (homebrew/core).`
`==> Updated Formulae`
`kerl`

`==> Installing msodbcsql from microsoft/mssql-release`
`==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz`

`curl: (56) Recv failure: Operation timed out`
`Error: Failed to download resource "msodbcsql"`
`Download failed: http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz`

This is my config of brew

`Byungkyus-Mac-Pro:~ bpark$ brew config`
`HOMEBREW_VERSION: 1.3.6`
`ORIGIN: https://github.com/Homebrew/brew`
`HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f`
`Last commit: 3 weeks ago`
`Core tap ORIGIN: https://github.com/Homebrew/homebrew-core`
`Core tap HEAD: 8d2303f426d783a9ea98dfc567c29a8e50ff9c88`
`Core tap last commit: 2 minutes ago`
`HOMEBREW_PREFIX: /usr/local`
`HOMEBREW_REPOSITORY: /usr/local/Homebrew`
`HOMEBREW_CELLAR: /usr/local/Cellar`
`HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com`
`CPU: 24-core 64-bit ivybridge`
`Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby`
`Clang: 8.0 build 800`
`Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git`
`Perl: /usr/bin/perl`
`Python: /Users/bpark/anaconda2/bin/python => /Users/bpark/anaconda2/bin/python2.7`
`Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby`
`Java: 1.8.0_151`
`macOS: 10.12.6-x86_64`
`Xcode: 8.2`
`CLT: 9.0.1.0.1.1506734476`
`X11: 2.7.112 => /opt/X11`

and curl version.

`Byungkyus-Mac-Pro:~ bpark$ curl --version`
`curl 7.55.1 (x86_64-apple-darwin13.4.0) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0`
`Release-Date: 2017-08-14`
`Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp `
`Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy`

Can you give me any suggestion?

Thank you.

**Comment by meet-bhagdev** [comment]
@mateusz-kmiecik @v-chojas @david-engel can you take a look?

**Comment by David-Engel** [comment]
@bpark76 I tried downloading the file that failed for you from a few different locations and it worked for me each time. Are you able to download the file from a browser to make sure it's not just your Internet connection?
http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz

**Comment by v-chojas** [comment]
The file is downloadable from here too, please check your Internet connection.

**Comment by bpark76** [comment]
@David-Engel I can download the file from safari and chrome.

But brew cannot download.

May it be something kinds of network security problem?

Thank you.

**Comment by v-chojas** [comment]
How about if you try to `curl` the file manually? Does it successfully download?

`curl http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz > msodbcsql-13.1.9.0.tar.gz`

**Comment by bpark76** [comment]
@v-chojas curl cannot download it.

`Byungkyus-Mac-Pro:BRCA2` bpark$ curl http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz > msodbcsql-13.1.9.0.tar.gz`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0`
`curl: (56) Recv failure: Operation timed out`

Thank you.

**Comment by v-chojas** [comment]
Are you behind a firewall and/or need a proxy to access the Internet? In Safari>Preferences>Advanced>Proxies you can see if there are any HTTP/S proxies configured.

You can also try using `curl` to download some other site, e.g. `curl https://github.com/` should retrieve the GitHub homepage source code.

**Comment by David-Engel** [comment]
Assuming this was a connectivity issue that has been fixed. Closing the issue. Feel free to reopen if there is still an issue.
