### ISSUE TITLE
odbcinst: SQLRemoveDriver failed with Unable to find component name.

### ISSUE THREAD

**Issue by RealcoJaneZheng** [microsoft/homebrew-mssql-release#62]
I am trying to install Microsoft ODBC driver 17 for SQL Server on macOS but I am getting the error. 

I am not sure how to fix this issue. Could anyone help me with that? Thank you very much in advance! 

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 mssql-tools
==> Checking for `sudo` access (which may request your password).
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown -R administrator:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 5c44aca2e Merge pull request #12365 from Homebrew/dependabot/bundler/Library/Homebrew/rubocop-performance-1.12.0
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (or will be during this `install` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
Already up-to-date.
Warning: HOMEBREW_NO_ENV_FILTERING is undocumented, deprecated and will be removed in a future Homebrew release (because it breaks many things)!
==> Downloading https://download.microsoft.com/download/1/9/A/19AF548A-6DD3-4B48
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/4e244e94bb2cf243bfb6a52aa7e894e6302f742b4a39a46aeab827c75e3661ca--msodbcsql17-17.8.1.1-amd64.tar.gz
==> Downloading https://download.microsoft.com/download/1/9/A/19AF548A-6DD3-4B48
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/4e244e94bb2cf243bfb6a52aa7e894e6302f742b4a39a46aeab827c75e3661ca--msodbcsql17-17.8.1.1-amd64.tar.gz
==> Downloading https://download.microsoft.com/download/F/D/1/FD16AA69-F27D-440E
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/647f6e1067f9bae2f6d5568ce5d08630eea5d36135c117922d8a857fc852a623--mssql-tools-17.8.1.1-amd64.tar.gz
==> Installing msodbcsql17 from microsoft/mssql-release
==> odbcinst -u -d -n "ODBC Driver 17 for SQL Server"
Last 15 lines from /Users/administrator/Library/Logs/Homebrew/msodbcsql17/01.odbcinst:
2021-11-02 15:26:02 +0000

odbcinst
-u
-d
-n
"ODBC Driver 17 for SQL Server"

odbcinst: SQLRemoveDriver failed with Unable to find component name.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/microsoft/homebrew-mssql-release/issues`

**Comment by v-chojas** [comment]
Are you using an ARM Mac? Have you seen https://github.com/microsoft/homebrew-mssql-release/issues/51 and other related issues here?

**Comment by v-chojas** [comment]
Is it an ARM machine or not? The output you've posted suggests it's not, or you may be running under Rosetta2 emulation.

**Comment by RealcoJaneZheng** [comment]
I don't think it is an ARM machine. The processor is 2.8 GHz Quad-Core Intel Core i7. I am not running under Rosetta2 emulation. Apologies if I misunderstood your question.

**Comment by v-chojas** [comment]
True, that is not ARM. Thus the paths are correct. Try to uninstall and reinstall from clean.
Note that due to https://github.com/microsoft/homebrew-mssql-release/issues/59 you may receive an OpenSSL error, in which case the workarounds suggested there should work.

**Comment by mediix** [comment]
@v-chojas, I seem to be having the above problem with ARM (Apple M1 Max) Chip!

Installed ODBC using homebrew. This is the output of `odbcinst -j`:

unixODBC 2.3.9
DRIVERS............: /opt/homebrew/etc/odbcinst.ini
SYSTEM DATA SOURCES: /opt/homebrew/etc/odbc.ini
FILE DATA SOURCES..: /opt/homebrew/etc/ODBCDataSources
USER DATA SOURCES..: /Users/xxx/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

I have also created symbolic links for `/etc/odbcinst.ini ` and `odbc.ini` files.

But I'm getting error when trying to connect:
`('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/homebrew/lib/libmsodbcsql.17.dylib' : file not found (0) (SQLDriverConnect)")`

Any idea?

**Comment by v-chojas** [comment]
Does the file /opt/homebrew/lib/libmsodbcsql.17.dylib exist?

**Comment by mediix** [comment]
I checked and it does exist. Would it possibly be permission issue?

**Comment by v-chojas** [comment]
It should be readable and executable by all users, at least, so I don't think so. You can use the `dtruss` tool to see what files it is trying to access when you attempt to connect, and which one it doesn't find. Usually the "file not found' message indicates either the file, or one of its dependencies, is not found.

**Comment by David-Engel** [comment]
Closing as inactive.
