### ISSUE TITLE
Error trying to run homebrew-mssql formula in mac OS Big Sur (M1)

### ISSUE THREAD

**Issue by raimundoloeser** [microsoft/homebrew-mssql-release#67]
Hi, 
I read that ODBC Driver for SQL Server was ready for mac with M1 and I'm trying to install it but I have not succeeded. I'm following this guide: 
https://github.com/microsoft/msphpsql/blob/master/Linux-mac-install.md#installing-the-drivers-on-macos

When I run the code indicated in the documentation of the Driver:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql17 ms
sql-tools` 

(https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15)

I get the following error:

<img width="569" alt="Captura de Pantalla 2022-01-14 a la(s) 12 13 33" src="https://user-images.githubusercontent.com/53836400/149540254-f90e8f85-2be9-4846-9fc8-1f7eb2f53f39.png">

Any help on this is highly appreciated.

**Comment by v-chojas** [comment]
Was mssql-preview mentioned anywhere in the docs? That's not the right one for installing this ODBC driver.

**Comment by raimundoloeser** [comment]
Nono, I tried another guides that makes me have that error

**Comment by v-chojas** [comment]
OK. If you find anything in the Microsoft docs that is giving wrong instructions, you are welcome to tell us and we can fix it.
