### ISSUE TITLE
Missing libmsodbcsql dependency?

### ISSUE THREAD

**Issue by njlr** [Microsoft/homebrew-mssql-release#7]
When I try to connect I get this error: 

```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Can't open lib '/usr/local/lib/libmsodbcsql.13.dylib' : file not found.
```

However, it seems to be already installed: 

```bash=
$ brew install msodbcsql 
Warning: microsoft/mssql-release/msodbcsql 13.1.9.0 is already installed
```

And here it is: 

```bash=
$ ls /usr/local/lib/libmsodbcsql.13.dylib 
/usr/local/lib/libmsodbcsql.13.dylib
```

**Comment by njlr** [comment]
For those looking for a quick work-around, I was able to use [DBeaver](https://dbeaver.jkiss.org/) over JDBC.

**Comment by David-Engel** [comment]
@v-makouz Can you take a look?

**Comment by v-makouz** [comment]
I just tried it on a clean El Capitan install and it seems to work correctly. 
There might be an issue with some local settings. After the installation of the driver brew should put the lib into /usr/local/Cellar/msodbcsql/13.1.9.0/lib/libmsodbcsql.13.dylib and create a symlink in /usr/local/lib/

It sounds like the symlink is missing for some reason, or maybe pointing at the wrong location, I would try

ls -l /usr/local/lib/libmsodbcsql.13.dylib

To see what's going on, maybe something overwrote or removed that file?

**Comment by mstein11** [comment]
I also got this issue. I checked the symlink and it seems to point to the right location as described by @v-makouz. 
Console output of ls -l: 
/usr/local/lib/libmsodbcsql.13.dylib -> ../Cellar/msodbcsql/13.1.9.0/lib/libmsodbcsql.13.dylib

Any suggestions on how to fix this?
