### ISSUE TITLE
Cannot tap microsoft/mssql-release: invalid syntax in tap!

### ISSUE THREAD

**Issue by farmerau** [microsoft/homebrew-mssql-release#73]
Hi there folks. In following the [docs for installing the Microsoft OBDC driver](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15#microsoft-odbc-18), I'm unable to move forward beyond tapping.

Specifically, the error I receive is: 

> Cannot tap microsoft/mssql-release: invalid syntax in tap!

## Entire execution output:

>==> Tapping microsoft/mssql-release
Cloning into '/usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release'...
remote: Enumerating objects: 257, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 257 (delta 8), reused 15 (delta 6), pack-reused 235
Receiving objects: 100% (257/257), 48.95 KiB | 771.00 KiB/s, done.
Resolving deltas: 100% (129/129), done.
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.5
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.2
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.3
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.4
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.1
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.6
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.8
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.9
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.7
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.0
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools18@18.0
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql18@18.0
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.1
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.6
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql@13.1
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.8
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.9
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.7
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.0
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.5
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.2
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.3
Error: Non-symlink alias: /usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.4
Error: Cannot tap microsoft/mssql-release: invalid syntax in tap!

## Brew Version
```shell
brew --version
Homebrew 3.4.6
Homebrew/homebrew-core (git revision 422f9e72088; last commit 2022-04-11)
Homebrew/homebrew-cask (git revision 9c215868cb; last commit 2022-04-11)
```

## MacOS Version
macOS Big Sur (Version 11.6.4) running on MacBook Pro (15-inch, 2019) (Intel)

Any guidance for how I might advance on this? Unfortunately, as a developer, I can't say that I'm overly familiar with how homebrew works from a packaging perspective-- only as a consumer.

**Comment by v-chojas** [comment]
https://github.com/microsoft/homebrew-mssql-release/tree/master/Aliases
These are correctly symlinks in the repo. Is your git configured to turn symlinks into regular files?

**Comment by Prankanyl** [comment]
@farmerau Thanks, it helped
