### ISSUE TITLE
My Mac(m1) cannot install Microsoft ODBC 18

### ISSUE THREAD

**Issue by Prankanyl** [microsoft/homebrew-mssql-release#74]
### In terminal
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install msodbcsql18 mssql-tools18
==> Checking for 'sudo' access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R user:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD сейчас на 09e766f83 Merge pull request #13156 from iMichka/security
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/user/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

==> Tapping microsoft/mssql-release
Cloning into '/opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release'...
remote: Enumerating objects: 257, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (12/12), done.
Receiving objects: 100% (257/257), 48.95 KiB | 385.00 KiB/s, done.
Resolving deltas: 100% (129/129), done.
remote: Total 257 (delta 8), reused 15 (delta 6), pack-reused 235
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.5
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.2
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.3
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.4
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.1
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.6
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.8
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.9
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.7
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.0
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools18@18.0
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql18@18.0
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.1
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.6
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql@13.1
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.8
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.9
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.7
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/mssql-tools@17.0
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.5
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.2
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.3
Error: Non-symlink alias: /opt/homebrew/Library/Taps/microsoft/homebrew-mssql-release/Aliases/msodbcsql17@17.4
Error: Cannot tap microsoft/mssql-release: invalid syntax in tap!
Already up-to-date.
Warning: HOMEBREW_NO_ENV_FILTERING is undocumented, deprecated and will be removed in a future Homebrew release (because it breaks many things)!
/opt/homebrew/Library/Homebrew/utils/popen.rb:55: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
/opt/homebrew/Library/Homebrew/language/python.rb:10: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Warning: No available formula with the name "msodbcsql18".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
`

What is the problem?

**Comment by v-chojas** [comment]
Git config not handling symlinks correctly? See https://github.com/microsoft/homebrew-mssql-release/issues/73 ?

**Comment by Prankanyl** [comment]
@v-chojas Thanks, it helped
