### ISSUE TITLE
MacOS infinite loop EULA prompt

### ISSUE THREAD

**Issue by David-Engel** [Microsoft/homebrew-mssql-release#8]
On macOS 10.11 and 10.12

Run

brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update

Then calling

ACCEPT_EULA=Y brew install --no-sandbox msodbcsql mssql-tools

does not remove the prompt to accept the EULA. Calling 

yes | ACCEPT_EULA=Y brew install --no-sandbox msodbcsql mssql-tools

causes the prompt to loop indefinitely because only YES or NO is accepted at the prompt. Setting the ACCEPT_EULA environment variable does not appear to have any effect.

Since this problem first occurred on 12/11 after the nightly builds, we suspect a homebrew-core update from a few hours later may have something to do with it.

**Comment by David-Engel** [comment]
This broke the setting of environment variables: https://github.com/Homebrew/brew/pull/3529

It can be overridden by setting HOMEBREW_NO_ENV_FILTERING=1.

Thus, following command will work to install:

HOMEBREW_NO_ENV_FILTERING=1 ACCEPT_EULA=Y brew install --no-sandbox msodbcsql mssql-tools

Remove "yes" from your command. It is not necessary and causes the infinite loop you described.

**Comment by David-Engel** [comment]
We will update mac installation docs to reflect the change in Homebrew.

**Comment by AceHack** [comment]
HOMEBREW_NO_ENV_FILTERING no longer works in the latest brew and ACCEPT_EULA=Y  seems to make no difference

**Comment by v-chojas** [comment]
Have you tried HOMEBREW_ACCEPT_EULA ? https://github.com/microsoft/homebrew-mssql-release/pull/85
(I know the name is misleading, as this is not about accepting Homebrew's EULA, but the naming was needed to workaround the env filtering.)
