### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by semcha** [microsoft/homebrew-mssql-release#83]
```
msodbcsql18 18.1.1.1
mssql-tools18 18.1.1.1
```

```
sqlcmd -S "HOST" -U "USER" -P "PASS" -d "DATABASE" -C -N -q "select @@version"
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection.
```

**Comment by v-chojas** [comment]
Could you give any more information? Was it working before and stopped working(and if so, did you do anything to cause it), is this your first time using it, what OS version, etc?

**Comment by semcha** [comment]
@v-chojas 
* First time using it
* MacOS 12.5.1 (M1)
* Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)

I found a solution for Ubuntu 20.04 - add lines to OpenSSL configuration file (`/etc/ssl/openssl.cnf`):
```
openssl_conf = default_conf

...

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1
```
But Ubuntu 20.04 works with OpenSSL 1.1.1 unlike the macOS brew driver which works with OpenSSL 3 and I have not found any way to join the server : (

**Comment by semcha** [comment]
The solution for OpenSSL 1.1.1 was found here:
https://github.com/microsoft/msphpsql/issues/1112#issuecomment-609972220

**Comment by v-chojas** [comment]
Are you sure it is a problem with OpenSSL and not e.g. firewall/network connectivity? 0x2746=10054 is a rather generic error (connection reset by peer.)

**Comment by v-chojas** [comment]
SQL 2016 supports TLS 1.2, and versions before that (down to 2008) have an update (KB3135244) which does. Thus I don't think that is the problem here, unless you have actually confirmed it with e.g. packet trace.

**Comment by hidayat-io** [comment]
i got same problem in macOS, any solution that working ?

**Comment by v-chojas** [comment]
See comment above, also this is a very generic error so if you don't provide any more details, this is the best we can tell you.

**Comment by v-chojas** [comment]
Open an issue with the details specific to your environment if you strongly believe it's a problem with the driver and eliminated other causes. Network errors are generic and troubleshooting those are outside the scope of this project.
