### ISSUE TITLE
I can't connect to SQL Server (MacBook Pro M1 Pro)

### ISSUE THREAD

**Issue by xsha256** [microsoft/homebrew-mssql-release#92]
I can't connect to SQL Server

```
import pyodbc

server = 'localhost'
database = 'bikerentdb'
username = 'sa'
password = 'Admin2020'

Connection String
driver = 'DRIVER={ODBC Driver 17 for SQL Server};'
#driver = '{Devart ODBC Driver for SQL Server}'
others = f"SERVER={server};DATABASE={database};UID={username};PWD={password}"
connection_string = '{}{}'.format(driver, others)

con = pyodbc.connect(connection_string)

cur = con.cursor()
res = cur.execute("SELECT @@VERSION AS 'SQL Server Version Details'")
for r in res:
print(r[0])
```

I'm getting this error:

` pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)') `

I have installed:
pyodbc 4.0.39
Python 3.11.3
mssql-tools
msodbcsql 17.10
Docker Version 4.18.0 => (Azure-sql-edge)

My system:
MacBook Pro M1 Pro Ventura 13.3.1

Thank you in advance.

**Comment by v-chojas** [comment]
localhost? There's no Mac version of SQL Server.

**Comment by xsha256** [comment]
i am using docker

**Comment by v-chojas** [comment]
In that case you shall need to understand how the network configuration of Docker is, because it sure isn't listening on localhost if you get that error. In any case this isn't a problem with the driver.

**Comment by flixman** [comment]
@v-chojas Your last statement is not correct. I have also found every now and then this problem with an M1 pro, like just yesterday, running SQLServer in docker (using rosetta) and msodbcsql 18.3.1.1. If I use the same string to connect to the sqlserver container through Azure Data Explorer, it just connects to it... so it seems to be related to the driver.
